before:
  hooks:
    - go mod tidy
builds:
  - id: macos_amd64
    binary: furlzz
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-L/tmp/data/macos_amd64/lib
      - CGO_CFLAGS=-I/tmp/data/macos_amd64/include  
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags: -s -w
  - id: macos_arm64
    binary: furlzz
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-L/tmp/data/macos_arm64/lib
      - CGO_CFLAGS=-I/tmp/data/macos_arm64/include
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -trimpath
    ldflags: -s -w
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
